In [ ]:
import numpy as np

data = np.array([[40, 35, 80],
                 [80, 50, 90],
                 [20, 55, 40],
                 [94, 80, 88],
                 [90, 30, 100]])
print('Input data (N, featuers):', data, data.shape)
N = data.shape[0]
n_dim = data.shape[1]
cov = np.zeros((n_dim, n_dim))

# E(X)
avg = []
for i in range(n_dim):
    avg.append(sum([d[i] for d in data]) / N)
print('avg', avg)

# covariance matrix
for i in range(n_dim):
    for j in range(n_dim):
        var = 0
        for d in data:
            var += (d[i] - avg[i]) * (d[j] - avg[j])
        var /= (N - 1)
        cov[i, j] = var
print('cov', cov)
print('numpy cov', np.cov(data, rowvar=False, bias=False))

Input data (N, featuers): [[ 40  35  80]
 [ 80  50  90]
 [ 20  55  40]
 [ 94  80  88]
 [ 90  30 100]] (5, 3)
avg [64.8, 50.0, 79.6]
cov [[1085.2  130.   670.4]
 [ 130.   387.5  -90. ]
 [ 670.4  -90.   540.8]]
numpy cov [[1085.2  130.   670.4]
 [ 130.   387.5  -90. ]
 [ 670.4  -90.   540.8]]
