**Numerical analysis and data manipulation using the numpy library**

***1.create a numpy array***

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


***2.Access and manipulates elements in the array***

In [ ]:
arr1[2]

3

In [ ]:
#chane an element from the array
arr1[2]=5
arr1

array([1, 2, 5])

***3.create a 2-dimensional array and check the shapes of the array***

In [ ]:
#create 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#check the shape of the array
print("the shape of 2 rows and 3 column:",arr2.shape)

the shape of 2 rows and 3 column: (2, 3)


***4.Access elements from the 2d array using index positions.***

In [ ]:
#accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


***5.create an array of the string***

In [ ]:
# array of type string
arr3=np.array(['india','china','usa','mexico'])
print(arr3)

['india' 'china' 'usa' 'mexico']


***6.using the arrange() and linespace() function to evenly space values in specified interval***

In [ ]:
# array of evenly spaced value within a specified interval
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# array of evenly space no in a specified interval
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


***7.create an array of random values between 0 and 1 in a given shape***

In [ ]:
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.01951485 0.55913521 0.54438097 0.62160331 0.36844141 0.5215554
 0.53593505 0.76011977 0.01918591 0.60247546]


[[0.36021674 0.42389705 0.37027332 0.9050331 ]
 [0.64816843 0.82077368 0.04359524 0.27820641]
 [0.29308195 0.77697733 0.43931553 0.82038561]]


***8.create an array of constant values in a given shape.***

In [ ]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


***9.repeat each elements of an array by a specified number of times using repeat() and tile() function.***

In [ ]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
#repeat an array by a specified number of times 
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


***10.create an identity using eye() and identity() function.***

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***11.create a 5x5 2d array for random number between 0 and 1***

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.36296456 0.18034735 0.84050035 0.50539573 0.00515271]
 [0.69930034 0.31002478 0.08529775 0.93383352 0.0026234 ]
 [0.78060218 0.86561184 0.32862027 0.63970835 0.50222837]
 [0.44817982 0.04423951 0.43344354 0.75533547 0.20870905]
 [0.22750189 0.88264869 0.37702669 0.18769593 0.46818775]]


***12.sum an array along the column.***

In [ ]:
print(np.sum(arr,axis=0))

[2.51854879 2.28287217 2.0648886  3.021969   1.18690128]


***13.sum an array along the row***

In [ ]:
print(np.sum(arr,axis=1))

[1.89436069 2.03107978 3.11677101 1.8899074  2.14306096]


***14.calculate the mean ,median,standard deviation, and varience***

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


0.44300719329534916
0.43344353872495456
0.2859724813665801
0.081780260098959


***15.sort an array along the row using the sort()function ***

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.04986838 0.10610905 0.2445894  0.93847247 0.15200976]
 [0.1688281  0.25944584 0.1860452  0.82951179 0.30430353]
 [0.78550159 0.66155593 0.53672287 0.84774717 0.62785348]
 [0.60751275 0.46389771 0.83976286 0.05170541 0.52898746]
 [0.09268526 0.18581819 0.72908549 0.31675366 0.34124947]]


In [ ]:
print(np.sort(arr,axis=1))

[[0.04986838 0.10610905 0.15200976 0.2445894  0.93847247]
 [0.1688281  0.1860452  0.25944584 0.30430353 0.82951179]
 [0.53672287 0.62785348 0.66155593 0.78550159 0.84774717]
 [0.05170541 0.46389771 0.52898746 0.60751275 0.83976286]
 [0.09268526 0.18581819 0.31675366 0.34124947 0.72908549]]


***16.append elements to an array using the append()function***

In [ ]:
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


***17.delete multiple elements in an array***

In [ ]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


***18.concatenation elements from 2 array***

In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
#combine array item by rows
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
